name: CI/CD EC2 Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Configure DNS
        run: |
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
        
      - name: Restart Docker
        run: sudo systemctl restart docker
        
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Build Docker image
        run: docker build -t AYOMITIDE-OAJ/jira-slack-backend-api .  
        
      - name: Publish image to Docker Hub
        run: docker push AYOMITIDE-OAJ/jira-slack-backend-api:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull image from Docker Hub
        run: docker pull AYOMITIDE-OAJ/jira-slack-backend-api:latest
        
      - name: Delete old container
        run: docker rm -f nodejs-app-container 
        
      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name nodejs-app-container AYOMITIDE-OAJ/jira-slack-backend-api
