name: CI/CD EC2 Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Print Docker version
        run: docker --version
        
      - name: Print login command (without executing)
        run: echo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Build docker image
        run: docker build -t AYOMITIDE-OAJ/jira-slack-backend-api .  
        
      - name: Publish image to docker hub
        run: docker push AYOMITIDE-OAJ/jira-slack-backend-api:latest
